### ISSUE TITLE
OSM às vezes não retorna dados

### ISSUE THREAD

**Issue by cmdalbem** [cmdalbem/ciclomapa#10]
![image](https://user-images.githubusercontent.com/467471/73884845-74ef3b00-4845-11ea-8940-31281e34c4e6.png)

Tive uma ideia pra mitigar esse problema e não deixar esse bug do OSM afetar nosso app. Vou adicionar uma regra que, se o OSM retornar vazio pra uma cidade que já tínhamos dados, então eu ignoro esse retorno (não sobreescrevo o banco de dados com isso), aviso o usuário que o OSM está passando por problemas desconhecidos e peço pra tentar novamente mais tarde.

**Comment by lguima** [comment]
Tem algum esquema de retry?

Por exemplo, tenta 3 vezes, se todas falharem, assume que realmente não retornou nada.

E quando não retornar nada, acho que não é válido "colocar a culpa" no OSM, a mensagem de erro ao usuário deveria ser algo relacionado a impossibilidade do Ciclomapa de buscar os dados atualizados e que estão sendo exibidos dados salvos anteriormente, talvez indicar a data.

**Comment by cmdalbem** [comment]
Não tem retry, o que tem é uma lista de servidores abertos do OSM que eu tento em paralelo e pego a resposta do primeiro que responder. Nós só acusamos falha total se nenhum servidor retornar dados.
O problema que estávamos tendo, que finalmente encontrarmos a razão essa semana, tem a ver com regiões "abertas" no OSM. Se alguém faz uma edição errada e deixa o intervalo aberto o filtro por Region ID que usamos pára de funcionar. Isso deve ser muito raro de acontecer, mas não temos como evitar.
Ou seja: eu podia implementar um retry e deixar o usuário mais tempo esperando antes de acusar o erro, mas pra esse problema que identificamos o retry não resolveria.

Sobre não "colocar a culpa" no OSM: pq vc acha isso?
Nas entrevistamos que estamos fazendo com usuários temos ouvido que não está clara a relação do CicloMapa com o OSM, de que os dados são colaborativos, e que eles são puxados direto de lá. Parece que sempre que for possível esclarecer essa fonte dos dados seria benéfico pra melhorar essa impressão. O que vc acha?

**Comment by lguima** [comment]
O que significa "deixar um intervalo aberto"?

Sobre a mensagem, o que eu quis dizer é que a falha foi do lado do CicloMapa na hora de atualizar os dados, então seria algo "Não foi possível atualizar os dados por uma falha na comunicação com o OSM" e não dizer que "o OSM está passando por problemas desconhecidos".

Indo na linha de deixar mais claro, dependendo da renderização da mensagem, pode ser válido incluir um texto/link explicando o que é o OSM e como o CicloMapa se integra (talvez a página da UCB).

**Comment by cmdalbem** [comment]
Implementado em https://github.com/cmdalbem/ciclomapa/commit/2265a63fe0e31da698addbbd42360db87da5c52f.
