### ISSUE TITLE
Add an open license

### ISSUE THREAD

**Issue by willemarcel** [cmdalbem/ciclomapa#2]
It would be good if we could license the code as GPL or other open source license

**Comment by lguima** [comment]
Concordo, faço parte de outro grupo que também tem uma plataforma e recentemente definimos uma licença open source para o projeto, com o intuito de incentivar a contribuição da comunidade.

A nossa plataforma foi viabilizada através de um financiamento coletivo, por isso procuramos uma licença que pudesse garantir que o código continuasse público.

Então escolhemos a **GPL 3.0**, a qual prevê que melhorias em distribuições sejam mantidas sob a mesma licença, garantindo que o código continue acessível.

**Comment by cmdalbem** [comment]
Obrigado pelo relato @lguima! To sentindo que é a melhor opção pra nós também, ainda mais se tratando de um projeto que também usa dados abertos, gosto da ideia de que qualquer coisa que seja criada em cima disso permaneça aberta.

**Comment by cmdalbem** [comment]
Resolvido em https://github.com/cmdalbem/ciclomapa/commit/d0294544cc6e221c87c570a9218b0a4098ed489c
