### ISSUE TITLE
Melhorias no estilo do mapa

### ISSUE THREAD

**Issue by willemarcel** [cmdalbem/ciclomapa#30]
![image](https://user-images.githubusercontent.com/666291/101995645-48e4e780-3caa-11eb-83b9-cd3f38531a10.png)
Link: https://ciclomapa.org.br/?lat=-12.9970274&lng=-38.4415860&z=16.52

Algumas sugestões para melhorar o estilo do mapa
- Mais contraste entre o solo e o oceano
- Ativar a visualização de parques (talvez um tom de verde escuro)
- Ativar a visualização de caminhos de pedestre (pode ser útil para traçar rotas alternativas ou identificar locais "people friendly")

**Comment by cmdalbem** [comment]
Obrigado pelas sugestões! Acho que faz sentido mesmo. O que vc acha assim?
![image](https://user-images.githubusercontent.com/467471/102421756-f9712500-3fe3-11eb-9dd5-3b344e207149.png)

Sobre caminhos de pedestre, acho que eles já estão habilitados, porém talvez muito sutil? Achei um exemplo aqui no Arpoador no Rio de Janeiro, vê se é disso que vc tá falando:
![image](https://user-images.githubusercontent.com/467471/102421972-76040380-3fe4-11eb-9ba6-3e3939a80229.png)

**Comment by willemarcel** [comment]
Gostei da cor dos parques! A cor do oceano também ficou boa.

Acho que esse estilo da Mapbox não inclui os dados de caminho de pedestre, que são essas linhas vermelhas tracejadas (em alguns casos pode ser compartilhada com ciclovia) https://www.openstreetmap.org/#map=19/-12.98912/-38.52174

**Comment by cmdalbem** [comment]
bah de fato a gente não tava mostrando de jeito nenhum quando era `type=footway`!
adicionei essa camada agora, com o mesmo estilo do `pedestrian`, o que tu acha?

![image](https://user-images.githubusercontent.com/467471/102489821-c57e1a00-404c-11eb-8ee7-9741171328e4.png)

**Comment by willemarcel** [comment]
Ficou excelente! Acho que você precisa ativar as camadas de bridge e tunnel para os caminhos de pedestre (tem uma ponte sobre o lago que não tá sendo mostrada).
Talvez seja útil ativar também a camada de labels para os parques

**Comment by cmdalbem** [comment]
de fato tava filtrando fora pontes, túneis etc. desliguei todos filtros agora, o que dei bastante match na cidade inteira mas acho que era esperado, né.

![image](https://user-images.githubusercontent.com/467471/102493968-b8fcc000-4052-11eb-94b4-fc83374e3214.png)

**Comment by cmdalbem** [comment]
Sobre labels, foi uma decisão nossa em um dado momento tirar _todas_ labels com exceção de nomes de ruas e de cidade, com o objetivo de limpar o mapa o máximo possível pro que importa pro ciclista. Nesse caso labels de parques ficariam fora também.
Dentre todos tipos de POI possíveis que o Mapbox oferece, vc acha que parques seria um em especial que deveria ter? Tem outras labels importantes que vc tb acha que deveriam estar no CicloMapa? Vou listar alguns exemplos de labels aqui que deixamos fora:
* hospital
* police
* park
* garden
* monument
* attraction
* etc...

**Comment by willemarcel** [comment]
> de fato tava filtrando fora pontes, túneis etc. desliguei todos filtros agora, o que dei vários matches na cidade inteira (linhas verdes destacadas) mas acho que era esperado, né.

Sim, aqui em Salvador tem algumas áreas em que as calçadas foram mapeadas como um caminho separado e notei também algumas passarelas.

> vc acha que parques seria um em especial que deveria ter?

Eu concordo em exibir poucas labels. Acho que em relação aos parques/praças, em alguns casos é tão importante quanto o nome de uma rua, principalmente quando é uma área de maior extensão.

**Comment by cmdalbem** [comment]
>Eu concordo em exibir poucas labels. Acho que em relação aos parques/praças, em alguns casos é tão importante quanto o nome de uma rua, principalmente quando é uma área de maior extensão.

bom ponto, faz sentido!

**Comment by cmdalbem** [comment]
@willemarcel muito obrigado por todas sugestões!
já estão no ar as mudanças sugeridas, inclusive com labels em todas praças e parques:

![image](https://user-images.githubusercontent.com/467471/102629044-6215ea00-4129-11eb-9667-c1078e7f9ab8.png)
