### ISSUE TITLE
Feature toggling

### ISSUE THREAD

**Issue by cmdalbem** [cmdalbem/ciclomapa#5]
Implementar alguma forma de habilitar condicionalmente certas features para simular um "ambiente de homologação" para testar novas funcionalidades em produção sem impactar usuários finais.
A solução poderia ser tão simples quanto um parâmetro de URL (tipo `/?env=beta`) que ativa uma variável global, que por conseguinte é testada pelas funcionalidades que queremos testar.

Exemplo: gostaríamos de poder habilitar facilmente a feature de mensuração de comprimentos de camadas (https://github.com/cmdalbem/ciclomapa/issues/7) em produção para a equipe testá-la, antes de lançá-la para o público geral.

**Comment by lguima** [comment]
Resgatando essa issue, ter um ambiente de homologação de fato não seria uma alternativa?

**Comment by cmdalbem** [comment]
Oi Lucas! Obrigado por me lembrar dessa issue, na realidade acho que estamos resolvidos com ela já. To usando Vercel, e ele cria deploys pra cada commit, o que tem ajudado bastante durante o desenvolvimento pra fazer esse tipo de coisa aí.
Em paralelo, estamos fechando negociações com ITDP Global para uma nova versão do CicloMapa mundial em que desenvolveremos um sistema de feature toggling mas com outro propósito: permitir diferentes países terem features específicas de cada um.
