### ISSUE TITLE
Dados do Rio de Janeiro (e outras cidades) não conseguem ser atualizados com OSM

### ISSUE THREAD

**Issue by mobilidados** [cmdalbem/ciclomapa#55]
Olá, Tudo bem?

Tentei atualizar os dados do Rio de Janeiro no ciclomapa, mas ele fica eternamente atualizando e não importa os dados do OSM. 

Estou tentando desde o dia 3 de janeiro até a presente data (5 de janeiro) e não consigo puxar os dados do OSM através do botão de atualizar dados do site. Ainda diz que são dados de 34 dias atrás. 

Não sei como resolver o problema, mas fica aqui o registro.

**Comment by cmdalbem** [comment]
Esse foi resolvido, mas Fortaleza agora não está funcionando

**Comment by alvesfelipe123** [comment]
Belo Horizonte também está com o mesmo problema.
