### ISSUE TITLE
Adição de região metropolitana de Lisboa

### ISSUE THREAD

**Issue by matheusgomesms** [cmdalbem/ciclomapa#75]
Opa pessoal,

Falando com o Felipe Alves, é capaz de eu ter de apresentar e dar um minicurso sobre mapeamento cicloviário para algumas cidades da região metropolitana de Lisboa (incluindo a capital).

Seria legal ter o Ciclomapa disponível nessas regiões, pois mostraria de maneira facilitada como anda a malha dessas cidades.

Uma facilidade é praticamente a não-necessidade de tradução hehe

(Issues relacionadas: #43 e #18).

**Comment by cmdalbem** [comment]
Oi @matheusgomesms 
Obrigado pelo contato, e desculpe a demora pra responder.
Parabéns pela oportunidade desse curso internacional!
Discutimos sua necessidade com a equipe mas infelizmente não é uma tarefa muito simples, porque além de envolver as issues que vc mencionou corretamente aqui ainda envolveria fazer o sistema roda em uma região que nunca testamos e precisaríamos fazer vários testes e talvez adaptações.
Não estamos com disponibilidade no momento pra implementar isso pra ti, porém o código é totalmente aberto, e se vc mesmo ou outra pessoa quiserem fazer isso e precisarem de ajuda pra tirar alguma dúvida estamos à disposição!

**Comment by matheusgomesms** [comment]
Obrigado pelo retorno, Cristiano!

Minha ideia era mais um showcase/propaganda, e se tivéssemos os dados da região teria mais apelo. De qualquer forma, tentarei mostrar, e se eles se interessarem em algo parecido podemos tentar forkar e desenvolver algo específico a eles.
