### ISSUE TITLE
Página da UCB redirecionando para outra vazia

### ISSUE THREAD

**Issue by lguima** [cmdalbem/ciclomapa#9]
O link para a [página do CicloMapa no site da UCB](https://www.uniaodeciclistas.org.br/atuacao/ciclomapa) está redirecionando para [outra página sem informações](https://uniaodeciclistas.org.br/banner/ciclomapa/).

**Comment by cmdalbem** [comment]
Obrigado @lguima ! Avisei o Felipe Alves da UCB, eles tão vendo isso do lado deles. Por enquanto vou tirar os links do CicloMapa pra não gerar dúvida :)
